import { useState } from 'react'
import { formatRelative, postsService, randomNoteRotation } from '../../lib/utils'
import type { PublicPost, ReportReason } from '../../types'
import { NOTE_COLOR_HEX, REPORT_REASONS } from '../../lib/constants'
interface StickyNoteProps { post: PublicPost; style?: React.CSSProperties; onClick?: () => void; className?: string; index?: number }
export const StickyNote = ({ post, style, onClick, className = '', index = 0 }: StickyNoteProps) => {
  const [reporting, setReporting] = useState(false); const [reason, setReason] = useState<ReportReason>('Offensive content'); const [message, setMessage] = useState<string | null>(null); const rotation = randomNoteRotation()
  const report = async () => { try { await postsService.submitReport(post.id, reason); setMessage('Thank you — the report was sent for review.'); setReporting(false) } catch (err: unknown) { setMessage(err instanceof Error ? err.message : 'Report could not be sent.') } }
  return <article className={`group relative flex w-full max-w-xs flex-col justify-between rounded-sm p-5 shadow-note transition-all duration-300 ease-note hover:-translate-y-1 hover:shadow-note-lift ${className}`} style={{ backgroundColor: NOTE_COLOR_HEX[post.note_color], transform: `rotate(${rotation})`, animationDelay: `${index * 60}ms`, ...style } as React.CSSProperties} onClick={onClick}><div className="absolute left-1/2 top-0 -translate-x-1/2 -translate-y-1/2"><span className="pin" /></div><div className="space-y-3 text-pretty"><p className="font-display text-sm font-semibold uppercase tracking-wide text-ink/80">TO: {post.recipient}</p><p className="whitespace-pre-wrap text-base leading-relaxed text-ink">{post.content}</p></div><div className="mt-4 flex items-end justify-between text-xs text-ink/70"><span className="font-hand text-base">— {post.author_display_name}</span><span>{formatRelative(post.created_at)}</span></div><div className="mt-3 border-t border-black/10 pt-2"><button type="button" disabled={post.reported_by_me} onClick={() => setReporting((value) => !value)} className="text-xs font-semibold text-ink/70 underline underline-offset-2 disabled:no-underline">{post.reported_by_me ? 'Reported' : 'Report note'}</button>{reporting && <div className="mt-2 flex gap-1"><select value={reason} onChange={(e) => setReason(e.target.value as ReportReason)} className="min-w-0 flex-1 rounded bg-white/70 px-1 text-xs">{REPORT_REASONS.map((item) => <option key={item}>{item}</option>)}</select><button type="button" onClick={() => void report()} className="rounded bg-rose-700 px-2 text-xs font-semibold text-white">Send</button></div>}{message && <p className="mt-2 text-xs font-semibold text-ink/80">{message}</p>}</div><div className="absolute right-3 top-2 h-10 w-16 rotate-[6deg] opacity-60 tape" /></article>
}